#! /bin/bash

# bitcoin user
# adduser bitcoin
# usermod -aG sudo bitcoin

# ############################################
# mount volume
# ############################################

export VOLUME_NAME=btc-node-volume
export MOUNT_POINT=/mnt/btc_node_volume

# NOTE: it might already be mounted?
# Mount your volume at the mount point:
# mount -o discard,defaults,noatime "/dev/disk/by-id/scsi-0DO_Volume_$VOLUME_NAME" $MOUNT_POINT
# Change fstab so the volume will be mounted after a reboot
# echo '/dev/disk/by-id/scsi-0DO_Volume_devbox-volume /mnt/devbox_volume ext4 defaults,nofail,discard 0 0' | sudo tee -a /etc/fstab
# symblink volume into home directory
# ln -s /mnt/devbox_volume ~/volume; sudo chown -R jcuffney:jcuffney /mnt/devbox_volume

# ############################################
# install bitcoin core
# ############################################

sudo snap install bitcoin-core

# create directory to store the blockchain history
mkdir /mnt/volume-lon1-03-part1/Bitcoin

# bitcoin.conf
mkdir ~/.bitcoin

# create bitcoin.service
sudo vi /lib/systemd/system/bitcoin.service

# start bitcoin.service
sudo service bitcoin start
