#! /bin/bash

# bitcoin user
# adduser bitcoin
# usermod -aG sudo bitcoin

# format and attach volume
sudo parted /dev/disk/by-id/scsi-0DO_Volume_volume-lon1-03 mklabel gpt
sudo parted -a opt /dev/disk/by-id/scsi-0DO_Volume_volume-lon1-03 mkpart primary ext4 0% 100%
sudo mkfs.ext4 /dev/disk/by-id/scsi-0DO_Volume_volume-lon1-03-part1
sudo mkdir -p /mnt/volume-lon1-03-part1
echo '/dev/disk/by-id/scsi-0DO_Volume_volume-lon1-03-part1 /mnt/volume-lon1-03-part1 ext4 defaults,nofail,discard 0 2' | sudo tee -a /etc/fstab
sudo mount -a
sudo chmod 777 /mnt/volume-lon1-03-part1

# install bitcoin core
sudo apt-add-repository ppa:bitcoin/bitcoin
sudo apt-get update
sudo apt-get install bitcoind

# create directory to store the blockchain history
mkdir /mnt/volume-lon1-03-part1/Bitcoin

# bitcoin.conf
mkdir ~/.bitcoin

# create bitcoin.service
sudo vi /lib/systemd/system/bitcoin.service

# start bitcoin.service
sudo service bitcoin start
